# Cours render à la main pour éviter que la compilation se fasse à chaque fois
source("_fun_render.R")
create_cmd("Cours")

enable_render()
remove_handout("Cours/_metadata.yml")
quarto::quarto_render('Cours/0_Accueil.qmd')
file.copy('_site/Cours/0_Accueil.pdf', 'Cours/pres/0_Accueil.pdf', overwrite = TRUE)
# file.copy('_site/Cours/0_Accueil.pdf', 'Cours/0_Accueil.pdf', overwrite = TRUE)
quarto::quarto_render('Cours/1_Rappels_R.qmd')
file.copy('_site/Cours/1_Rappels_R.pdf', 'Cours/pres/1_Rappels_R.pdf', overwrite = TRUE)
quarto::quarto_render('Cours/2_Analyse_Graphique.qmd')
file.copy('_site/Cours/2_Analyse_Graphique.pdf', 'Cours/pres/2_Analyse_Graphique.pdf', overwrite = TRUE)
quarto::quarto_render('Cours/3_Decomposition.qmd')
file.copy('_site/Cours/3_Decomposition.pdf', 'Cours/pres/3_Decomposition.pdf', overwrite = TRUE)
quarto::quarto_render('Cours/4_Lissage_Exponentiel.qmd')
file.copy('_site/Cours/4_Lissage_Exponentiel.pdf', 'Cours/pres/4_Lissage_Exponentiel.pdf', overwrite = TRUE)
quarto::quarto_render('Cours/5_ARIMA.qmd')
file.copy('_site/Cours/5_ARIMA.pdf', 'Cours/pres/5_ARIMA.pdf', overwrite = TRUE)
quarto::quarto_render('Cours/6_Complements.qmd')
file.copy('_site/Cours/6_Complements.pdf', 'Cours/pres/6_Complements.pdf', overwrite = TRUE)

add_handout("Cours/_metadata.yml")
# quarto::quarto_render('Cours/0_Accueil.qmd')
quarto::quarto_render('Cours/1_Rappels_R.qmd')
file.copy('_site/Cours/1_Rappels_R.pdf', 'Cours/1_Rappels_R.pdf', overwrite = TRUE)
quarto::quarto_render('Cours/2_Analyse_Graphique.qmd')
file.copy('_site/Cours/2_Analyse_Graphique.pdf', 'Cours/2_Analyse_Graphique.pdf', overwrite = TRUE)
quarto::quarto_render('Cours/3_Decomposition.qmd')
file.copy('_site/Cours/3_Decomposition.pdf', 'Cours/3_Decomposition.pdf', overwrite = TRUE)
quarto::quarto_render('Cours/4_Lissage_Exponentiel.qmd')
file.copy('_site/Cours/4_Lissage_Exponentiel.pdf', 'Cours/4_Lissage_Exponentiel.pdf', overwrite = TRUE)
quarto::quarto_render('Cours/5_ARIMA.qmd')
file.copy('_site/Cours/5_ARIMA.pdf', 'Cours/5_ARIMA.pdf', overwrite = TRUE)
quarto::quarto_render('Cours/6_Complements.qmd')
file.copy('_site/Cours/6_Complements.pdf', 'Cours/6_Complements.pdf', overwrite = TRUE)

unlink("_site/Cours", recursive = TRUE)

disable_render()

quarto::quarto_publish_site()
